### ISSUE TITLE
表格位置

### ISSUE THREAD

**Issue by Han814** [SuikaXhq/seu-bachelor-thesis-2022#14]
表格位置好像有点问题，要不在这一页最顶上要不就在最下面，兄弟要不看看

**Comment by SuikaXhq** [comment]
可以提供一个最小可复现例子（Minimum Workable Example）吗？我这里是正常的。
另外，如果你不需要表格的浮动，可以参考一下使用手册6.1节。

**Comment by Han814** [comment]
啊抱歉，取消浮动就正常了
