### ISSUE TITLE
三个小问题想请教

### ISSUE THREAD

**Issue by liqingyang665** [SuikaXhq/seu-bachelor-thesis-2022#17]
1、请问windows下怎么使用全局编号（图表公式），能给个示例么？
2、公式中的字母和数字，如何调成Times New Roman字体格式，同时不影响text中的字体（有些包调了好像会冲突）
3、每一章标题、每一级目录小标题的行距如何调整？如何调整使得页眉和页面最顶端的字的间距拉大？

**Comment by SuikaXhq** [comment]
1. 请参考使用手册第4节，如需图表公式均使用全局编号可尝试：
```latex
\documentclass[globalcaption]{seuthesis-2022}
```
2. 模板类里没有提供这种选项，可以考虑mathtime或者XITS等包，具体使用方法可以搜索相关文档。若有冲突请提供一个MWE以及报错信息。
3. 调整单独某标题的垂直间距可以使用`\vspace`命令，如`\vspace{5pt}`，放置于想要调整的位置，负数长度可以缩短间距。若想同时调整所有标题间距，请参考使用手册10.10节代码第302-303行，对你下载的cls文件进行修改。页眉与正文的间距由`geometry`宏包控制，可以参考使用手册10.5节代码第189行以及[这个链接](https://tex.stackexchange.com/questions/132170/what-do-headheight-headsep-etc-do-in-the-vmargin-package)，修改headsep的值。

**Comment by liqingyang665** [comment]
非常感谢！二三没有问题，第一个我试过了，不过没反应也没有报错。。

**Comment by SuikaXhq** [comment]
仔细检查了下发现是忘记在globalcaption里把globaleq同时启用 你可以试一下`\documentclass[globalcaption,globaleq]{seuthesis-2022}`

**Comment by liqingyang665** [comment]
> 

感谢，试了一下，这样实现的是每一章的全局编号，如果想要全文（包括附录）的全局编号可以设置么请问？

**Comment by SuikaXhq** [comment]
抱歉，之前在实现的时候没有仔细检查，在[1.0.6版release](https://github.com/SuikaXhq/seu-bachelor-thesis-2022/releases/tag/1.0.6)里已经修复了这个问题，现在使用`globalcaption`选项就可以实现全文全局编号了。

**Comment by liqingyang665** [comment]
> 

这个在我一开始提问的时候您回答过我了诶，我试了还是按照章来编号的，也不知道为什么hhh

**Comment by SuikaXhq** [comment]
我的意思是我刚更新了一个版本的模板类，您可以更新一下试试
