### ISSUE TITLE
2024版本科毕设能否更新？

### ISSUE THREAD

**Issue by ZhangYezhuo** [SuikaXhq/seu-bachelor-thesis-2022#19]
2024新版的毕业设计word模板已推出，封面和部分格式有所变化，请问是否可以更新一个2024版本呢？

**Comment by SuikaXhq** [comment]
能否告知一下具体的变化是什么呢？此外我近几月可能会比较忙所以可能不能第一时间更新，如果急用的话可以考虑自行修改

**Comment by ZhangYezhuo** [comment]
> 能否告知一下具体的变化是什么呢？此外我近几月可能会比较忙所以可能不能第一时间更新，如果急用的话可以考虑自行修改

封面有了一点格式的变化，比如换了logo和文字等，其他改动不大，详见https://jwc.seu.edu.cn/2024/0117/c21686a479303/page.htm 。我已自行修改了，感谢！
