### ISSUE TITLE
LYX使用

### ISSUE THREAD

**Issue by Shelby-Hub-Southeast** [SuikaXhq/seu-bachelor-thesis-2022#21]
您好，请问我在lyx2.3.7导入tex文件时出现报错：
LyX: 无法转换文件 执行此程序时出错: D:/texlive/2023/bin/windows/LyX 2.3/bin/tex2lyx" -f "sample thesis.tex' sample thesis.lyx
请问有办法解决吗

**Comment by SuikaXhq** [comment]
没有使用过lyx，是否有更详细的报错信息？

**Comment by Shelby-Hub-Southeast** [comment]
没有，就是弹出这样一个窗口。我还注意到.bat文件编译后会生成.lyx文件不过这个文件也是空白的。没关系我用tex写也可以
