### ISSUE TITLE
二级节标题格式有误

### ISSUE THREAD

**Issue by marszhaang** [SuikaXhq/seu-bachelor-thesis-2022#22]
二级节标题（如，2.1.1 实验方法）：小四号宋体居左。
<img width="398" alt="Screenshot 2024-05-17 at 01 07 54" src="https://github.com/SuikaXhq/seu-bachelor-thesis-2022/assets/123704076/a9495991-8310-48c9-950f-bd9baea715f9">

**Comment by SuikaXhq** [comment]
这里的格式为了和正文有一定区分设置了小四号宋体加粗居左，如果不想要加粗可以自行修改。
