### ISSUE TITLE
关于引用的问题

### ISSUE THREAD

**Issue by xychen0335** [SuikaXhq/seu-bachelor-thesis-2022#23]
natbib被改成默认上标了吗

**Comment by SuikaXhq** [comment]
这个应该是gbt7714包的默认行为，参考：[gbt7714 Document](https://mirrors.bfsu.edu.cn/CTAN/biblio/bibtex/contrib/gbt7714/gbt7714.pdf)

**Comment by xychen0335** [comment]
已经解决，谢谢。
